Updating install to turnip's version.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -6,8 +6,23 @@
 #
 source bin/.config
 
-# Run the rebuild script.
-bin/rebuild
+BUILD=1
+TEST=1
+
+# Parse flags to disable portions of script.
+for i in $*; do
+  if [[ $i = "--nobuild" ]] || [[ $i = "-nb" ]]; then
+    BUILD=0
+  fi
+  if [[ $i = "--nohat" ]] || [[ $i = "-nh" ]]; then
+    TEST=0
+  fi
+done
+
+if [[ $BUILD = 1 ]]; then
+  # Run the rebuild script.
+  bin/rebuild
+fi
 
 if ! ( test -e drupal ); then
   echo "I didn't find a drupal directory. Are you sure it exists?"
@@ -16,10 +31,15 @@ fi
 
 # Site install.
 if [[ -e db/production_current.sql.gz ]]; then
+  echo "Loading from production database copy."
   cd db
   ./db_load.sh production_current.sql.gz
   cd -
+  cd drupal
+    drush updatedb -y
+  cd -
 else
+  echo "Installing Drupal using profile $PROFILE"
   cd drupal
   drush site-install -y --uri=default $PROFILE
   drush fra -y
@@ -27,35 +47,42 @@ else
   cd -
 fi
 
-# Enable modules I use locally every time.
-# TODO read this from local config instead of hard-coding.
+# Enable modules developer modules.
 # TODO use drush aliases
 cd drupal
-drush en diff -y
-drush en views_ui -y
-drush en styleguide feeds_ui -y
+: ${TURNIP_DEVELOPER_MODULES:="devel diff styleguide views_ui"}
+drush en -y $TURNIP_DEVELOPER_MODULES
+
+# Enable stage file proxy module.
+if [ "$PRODUCTIONURL" != "http://" ]; then
+  echo "Enabling Stage File Proxy and configuring origin as '$PRODUCTIONURL'."
+  drush en -y stage_file_proxy
+  drush vset stage_file_proxy_origin $PRODUCTIONURL
+fi
 cd -
 
-# Run behat.
-cd bdd
-# Check for composer, or install
-`command -v composer > /dev/null 2>&1`
-if [[ $? -gt 0 ]]; then
-  # Install locally.
-  if [[ ! -e composer.phar ]]; then
-    curl -sS https://getcomposer.org/installer | php
+if [[ $TEST = 1 ]]; then
+  # Run behat.
+  cd bdd
+  # Check for composer, or install
+  `command -v composer > /dev/null 2>&1`
+  if [[ $? -gt 0 ]]; then
+    # Install locally.
+    if [[ ! -e composer.phar ]]; then
+      curl -sS https://getcomposer.org/installer | php
+    fi
+    composer_command=./composer.phar
+  else
+    composer_command=composer
   fi
-  composer_command=./composer.phar
-else
-  composer_command=composer
-fi
 
-if [[ ! -e bin/behat ]]; then
-  $composer_command install
-fi
+  if [[ ! -e bin/behat ]]; then
+    $composer_command install
+  fi
 
-if [[ -e behat.local.yml ]]; then
-  bin/behat
-else
-  echo "Cannot run behat tests until bdd/behat.local.yml exists! Copy bdd/behat.local.yml.example into place to get started."
+  if [[ -e behat.local.yml ]]; then
+    bin/behat
+  else
+    echo "Cannot run behat tests until bdd/behat.local.yml exists! Copy bdd/behat.local.yml.sample into place to get started."
+  fi
 fi
